# Labels based on PR title
'type: refactoring 🛠':
  title: '^refactor(\(.+\))?:.*'
'type: bug / fix 🐞':
  title: '^(run)?fix(\(.+\))?:.*'
'type: chore 🧹':
  title: '^chore(\(.+\))?:.*'
'type: documentation 📋':
  title: '^docs(\(.+\))?:.*'
'type: feature / request ✨':
  title: '^feat(\(.+\))?:.*'
'type: test 👷':
  title: '^test(\(.+\))?:.*'

# Labels based on changed files
'package: api-client':
  files:
    - 'packages/api-client/.*'
'package: bazinga64':
  files:
    - 'packages/bazinga64/.*'
'package: bot-api':
  files:
    - 'packages/bot-api/.*'
'package: bot-handler-avs':
  files:
    - 'packages/bot-handler-avs/.*'
'package: bot-handler-debug':
  files:
    - 'packages/bot-handler-debug/.*'
'package: bot-handler-uptime':
  files:
    - 'packages/bot-handler-uptime/.*'
'package: bot-handler-wizard':
  files:
    - 'packages/bot-handler-wizard/.*'
'package: cbor':
  files:
    - 'packages/cbor/.*'
'package: changelog-bot':
  files:
    - 'packages/changelog-bot/.*'
'package: cli-client':
  files:
    - 'packages/cli-client/.*'
'package: commons':
  files:
    - 'packages/commons/.*'
'package: copy-config':
  files:
    - 'packages/copy-config/.*'
'package: core':
  files:
    - 'packages/core/.*'
'package: cryptobox':
  files:
    - 'packages/cryptobox/.*'
'package: eslint-config':
  files:
    - 'packages/eslint-config/.*'
'package: license-collector':
  files:
    - 'packages/license-collector/.*'
'package: lru-cache':
  files:
    - 'packages/lru-cache/.*'
'package: prettier-config':
  files:
    - 'packages/prettier-config/.*'
'package: priority-queue':
  files:
    - 'packages/priority-queue/.*'
'package: proteus':
  files:
    - 'packages/proteus/.*'
'package: react-ui-kit':
  files:
    - 'packages/react-ui-kit/.*'
'package: store-engine':
  files:
    - 'packages/store-engine/.*'
'package: store-engine-bro-fs':
  files:
    - 'packages/store-engine-bro-fs/.*'
'package: store-engine-dexie':
  files:
    - 'packages/store-engine-dexie/.*'
'package: store-engine-fs':
  files:
    - 'packages/store-engine-fs/.*'
'package: store-engine-sqleet':
  files:
    - 'packages/store-engine-sqleet/.*'
'package: store-engine-web-storage':
  files:
    - 'packages/store-engine-web-storage/.*'
'package: travis-bot':
  files:
    - 'packages/travis-bot/.*'
'package: webapp-events':
  files:
    - 'packages/webapp-events/.*'
'comp: infrastructure':
  files:
    - 'bin/.*'
    # All top-level files and folders starting with a dot
    - '\..*'
    # All top-level JSON files
    - '^[^\/]+\.json$'
    # All top-level YAML files
    - '^[^\/]+\.yml$'
