version: 2.1

orbs:
  win: circleci/windows@1.0.0

workflows:
  version: 2
  build:
    jobs:
      - build_test_windows

jobs:
  build_test_windows:
    executor: win/vs2019
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn boot
      - run: yarn test
