name: Test, Build and release hotfix version of packages

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test_build_release_hotfix:
    uses: ./.github/workflows/reusable_release.yml
    secrets: inherit
    with:
      mode: hotfix
