name: Test, Build and release beta version of packages

on:
  workflow_dispatch:
    inputs:
      preid:
        description: 'Prerelease identifier.'
        default: 'beta'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  test_build_release_beta:
    uses: ./.github/workflows/reusable_release.yml
    secrets: inherit
    with:
      mode: beta
      preid: ${{ inputs.preid }}
