name: Test, Build and release hotfix version of packages

on:
  workflow_dispatch:

permissions:
  id-token: write # Required for npm Trusted Publishing
  contents: write

jobs:
  test_build_release_hotfix:
    runs-on: ubuntu-latest
    env:
      COMMITTER: ${{github.event.head_commit.committer.name}}
      COMMIT_URL: ${{github.event.head_commit.url}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.OTTO_THE_BOT_GH_TOKEN }}

      - name: Set environment variables
        run: |
          echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
          echo "TAG=$(git tag --points-at ${{github.sha}})" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{github.event.after}} | head -n 1)" >> $GITHUB_ENV

      - name: Set TITLE
        env:
          PR_TITLE: ${{github.event.pull_request.title || env.COMMIT_MESSAGE}}
        run: echo "TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Print environment variables
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo -e "BRANCH_NAME = ${BRANCH_NAME}"
          echo -e "TAG = ${TAG}"
          echo -e "TITLE = ${TITLE}"
          echo -e "COMMIT_MESSAGE = ${COMMIT_MESSAGE}"
          echo -e "COMMIT_URL = ${COMMIT_URL}"
          echo -e "COMMITTER = ${COMMITTER}"
          echo -e "HOME = ${HOME}"
          echo -e "GITHUB_CONTEXT = ${GITHUB_CONTEXT}"

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{github.token}}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'yarn'

      # Auth is provided via checkout token; no separate netrc needed

      - name: Install JS dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test

      - name: Release hotfix versions (Trusted Publishing)
        run: |
          # Enable npm provenance and use GitHub OIDC (npm Trusted Publishing)
          npm config set provenance true
          npm config set registry https://registry.npmjs.org/
          git config --global user.email webapp+otto@wire.com
          git config --global user.name "Otto the Bot"
          yarn hotfix-release
